### ISSUE TITLE
this plugin appears to add another magneto login to a site.

### ISSUE THREAD

**Issue by positive-tdh** [r-martins/Magento-OutOfStockSubscription#1]
which is a surprise to people when the main admin login panel is behind protection.
example.com/outofstocksubscription/adminhtml_subscriber/index/

**Comment by r-martins** [comment]
Sorry for the delay in replying to you.
It's the default behaviour of magento.
If you visit example.com/admin/sales_order/index/ you'll also see a "another magento login".
After login in you'd be redirected to the admin route of sales>orders.
Feel free to audit \BusinessKing_OutofStockSubscription_Adminhtml_SubscriberController::indexAction controller. 
;)
